# Generated by Django 6.0.6 on 2026-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0006_order_payment_id_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cod', 'Cash on Delivery')], default='stripe', max_length=20),
        ),
    ]
